Feat/#27684282 privacy policy
LiyaVysotskaya/Feature-lab-front pull request #23
Opened 2024-01-18 18:02 UTC by PSKutergin

2024-01-21 12:40 UTC, LiyaVysotskaya requested changes

2024-01-21 12:40 UTC, LiyaVysotskaya commented on src/components/PopupPrivacyPolicy/PopupPrivacyPolicy.module.scss
> +  &__text {
Для 1920px в макете другие значения: 
![image](https://github.com/LiyaVysotskaya/Feature-lab-front/assets/121226479/10d1dacb-01cc-4747-9456-60d81cb51cea)

2024-01-21 12:40 UTC, LiyaVysotskaya commented on src/components/PopupPrivacyPolicy/PopupPrivacyPolicy.tsx
> +        <button
Нужно достать кнопку из ui-кита

2024-01-31 11:47 UTC, chepash commented
![image](https://github.com/LiyaVysotskaya/Feature-lab-front/assets/100382249/f4601c80-f8d1-4afa-a053-f08fbb6415de)
Надо бы оцентровать

2024-01-31 11:59 UTC, chepash commented
https://github.com/LiyaVysotskaya/Feature-lab-front/assets/100382249/01ee2e2b-6db3-4382-9aeb-3282aff4cb78

не знаю даже баг это или фича:
- двойной скролл справа
- поведение при скролле, сначала проматывается модалка, затем начнёт проматываться сам сайт за модалкой

2024-01-31 12:04 UTC, chepash requested changes
![image](https://github.com/LiyaVysotskaya/Feature-lab-front/assets/100382249/083d6edb-f7b6-40ac-91a3-0e3274aba984)
Надо бы оцентровать

2024-01-31 12:13 UTC, chepash requested changes

2024-01-31 12:13 UTC, chepash commented on src/components/PopupPrivacyPolicy/PopupPrivacyPolicy.module.scss
> +      font-weight: var(--text-1-line-font-weight, 400);
![image](https://github.com/LiyaVysotskaya/Feature-lab-front/assets/100382249/7915c004-a3bb-44f8-9156-997c17354ed1)

избавиться от всех переменных относящихся к размеру. 
Оставить только переменных относящиеся к цвету.

2024-01-31 12:26 UTC, chepash commented on src/components/PopupPrivacyPolicy/PopupPrivacyPolicy.module.scss
> +  // padding-top: 50px;
лишние комменты

2024-01-31 12:29 UTC, chepash requested changes

2024-01-31 12:29 UTC, chepash commented on src/components/PopupPrivacyPolicy/PopupPrivacyPolicy.module.scss
> +  // padding-top: 50px;
лишние комменты

2024-02-21 12:58 UTC, chepash approved these changes

2024-02-21 12:58 UTC, merged