Feat/#26874281 competencies team slider
LiyaVysotskaya/Feature-lab-front pull request #26
Opened 2024-02-02 11:35 UTC by niramov

2024-02-02 13:48 UTC, chepash requested changes
Еще желательно вставить свой компонент в CompetencePage с прокинутым готовым стилем для отступа между секциями. Чтобы визуально его глянуть сразу.

2024-02-02 13:48 UTC, chepash commented on src/components/TeamSlider/TeamSlider.tsx
> +      <h2 className={s.sectionTitle}>Команда</h2>
h2 заголовок хорошо бы заменить на компонент SectionTitle чтобы было единообразие с остальными секциями при адаптиве.

Ну и стили потом почистить.

2024-02-02 13:48 UTC, chepash commented on src/components/TeamSlider/TeamSlider.module.scss
> +  margin: 0 0 200px;
Убрать отступ снизу.
За это будет отвечать родитель, в который твой компонент импортируется.

Не забыть их убрать и во всех медиа запросах.

2024-02-05 08:56 UTC, niramov commented on src/components/TeamSlider/TeamSlider.tsx
> +      <h2 className={s.sectionTitle}>Команда</h2>
Заменил

2024-02-05 08:56 UTC, niramov commented on src/components/TeamSlider/TeamSlider.module.scss
> +  margin: 0 0 200px;
Убрал отступы, включая медиазапросы

2024-02-05 09:29 UTC, chepash requested changes
![image](https://github.com/LiyaVysotskaya/Feature-lab-front/assets/100382249/7b97c410-6022-49d3-b893-7e65a9dcab5f)


проблема с плотным расположением слайдов. Они стали плотенее друг к другу, но по сути остались те же по ширине и рендерятся поверх друг друга. Из-за этого нельзя кликнуть по накрытой части соседнего слайдера.

Не знаю как лучше решить. 
Либо не давать им плотно сближаться.
Либо попробовать сделать круговой градиент вокруг слайда "вне потока". Как у кнопки большой.
Либо побаловаться с z-index в нужных местах.
Либо это это два слайдера. Один слайдер сзади со всем круговыми градиентами, а спереди второй слайдер со всекм карточками(фото+текст)

2024-02-05 09:32 UTC, chepash requested changes
![image](https://github.com/LiyaVysotskaya/Feature-lab-front/assets/100382249/4d6362c3-51cf-4434-80ca-2296303edbb5)

возможно стоит отображать по одному сладу пораньше. Уже при ширине 563px они картинками и текстом друг на друга наезжают.

2024-02-05 09:40 UTC, chepash requested changes
![image](https://github.com/LiyaVysotskaya/Feature-lab-front/assets/100382249/b0415caf-6a3f-4d20-99fe-7b6c9a758fd2)

когда слайд один, он почему-то по правому краю выравнивается. А не по центру.

2024-03-18 13:44 UTC, LiyaVysotskaya requested changes

2024-03-18 13:44 UTC, LiyaVysotskaya commented on src/components/TeamSliderSection/CarouselBtn/CarouselBtn.module.scss
> +    --size: 44px;
Нужно уменьшить кнопки для мобилок пораньше, например, на 690px:
![image](https://github.com/LiyaVysotskaya/Feature-lab-front/assets/121226479/f41246b1-08f7-45ec-9df9-0a950ed4eac0)

2024-03-18 13:44 UTC, LiyaVysotskaya commented on src/components/TeamSliderSection/TeamSliderSection.tsx
> +  return (
Нужно добавить по краям экрана элемент, отвечающий за "затухание", чтобы картинки не обрывались резко. Он должен перекрывать обрезанные слайды, чтобы на них не срабатывал hover и смена картинки, но не лез на кнопки переключения слайдов

2024-03-18 18:19 UTC, chepash approved these changes

2024-03-19 10:00 UTC, LiyaVysotskaya approved these changes

2024-03-19 10:01 UTC, merged