Feat/#26595676 competencies
LiyaVysotskaya/Feature-lab-front pull request #6
Opened 2023-12-14 20:01 UTC by chepash

Если хочется чтобы сайт не скакал снизу. То нужно заранее знать какое количество пунктов будет в этой секции. Чтобы зафиксировать высоту.

так как overflow hidden будет работать только с зафиксированоой по высоте секцией.

2023-12-15 08:15 UTC, KazakovMaksim commented
как выгдялит и работает мне очень нравится. Пока бросилось в глаза, что в крайней нижней компетенции на 1920 обрезается текст как для верхних секций в отличие от макета, где этого нет.

2023-12-15 12:32 UTC, KazakovMaksim requested changes

2023-12-15 12:32 UTC, KazakovMaksim commented on src/components/Main/Main.tsx
> +      <Promo />
не понял, зачем еще раз добавлен Promo без удаления нижнего?

2023-12-15 20:58 UTC, chepash commented on src/components/Main/Main.tsx
> +      <Promo />
это я для ревью добавил. Чтобы вы оценили как контент скакать после этой секции будет.

2023-12-16 05:24 UTC, KazakovMaksim commented on src/components/Main/Main.tsx
> +      <Promo />
ок, теперь понял, что ты имел в виду.

2023-12-16 05:29 UTC, KazakovMaksim approved these changes

2023-12-16 05:29 UTC, merged